### PR TITLE
Refactor habit store

### PR DESCRIPTION
**Pull request by devinjameson**
Why: we would like for the habit store to be hydrated before the navigation mounts. This would remove the need to run a side effect on the home screen to get the habits from async storage and then update the habit store. We would also like to store the habit store to async storage whenever any of its observables updates.

This commit:
- Refactors the habit store and adds a method to hydrate the store
- Hydrates the store before mounting the navigation
- Adds `autorun` to store the habit store to async storage whenever one of the habit store observables changes

### CODE REVIEW

**Comment by devinjameson** [comment]
@johnschoeman As a next step, thoughts on using `autorun` to update async storage so we don't have to do `Storage.storeHabitStore(nextHabits)` each time we run an action?

**Comment by devinjameson** [comment]
> @johnschoeman As a next step, thoughts on using `autorun` to update async storage so we don't have to do `Storage.storeHabitStore(nextHabits)` each time we run an action?

Ended up doing this in this PR.

**Review by johnschoeman — COMMENTED** [review]
Nice! Anyway we can get away from the decorators? Seems like the industry is moving away from those in favor of regular functions

**Comment by devinjameson** [comment]
> Nice! Anyway we can get away from the decorators? Seems like the industry is moving away from those in favor of regular functions

It's possible, but the syntax looks pretty weird to my eye: https://github.com/pinqy520/mobx-persist

**Pull request merged**
